import type { NextPage } from 'next'
import Head from 'next/head'
import { ProfileScreen } from '~/components/screens/ProfileScreen'

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ProfileScreen />
    </>
  )
}

export default Page
